### ISSUE TITLE
on_completion hook with failure_cancels_group set to false does not fire with any failures.

### ISSUE THREAD

**Issue by surjay** [salsify/delayed_job_groups_plugin#12]
It seems like the on_completion hook is acting more like an "on_success" hook, even with `failure_cancels_group` set to false.  I think in situations where you have a group of jobs configured to not cancel the group with any failures that you also would/could want your on_completion job to still fire.

My use-case is I have large groups of jobs where I know some jobs are likely to fail but I want the entire group to still process AND i want my on_completion job to still fire for some post-processing/cleanup work I need to do.

I would propose either 

A) adding an additional option to to allow this. Something like: `failure_completes_group` which defaults to false for backwards compatibility and works in tandem with `failure_cancel_groups`

OR

B) tweaking the hooks by adding a true on_success hook that behaves like on_complete does today and changing on_complete to always fire IF the entire group is not canceled

OR

C) adding a new "on_finish" hook or something similar that always fires if/when the group is not canceled and leaving on_completion unchanged..

I'd be happy to submit the PR for this but wanted to gauge interest and/or get a consensus on implementation first.

**Comment by jturkel** [comment]
@surjay - The intent of the `on_completion` was to work exactly like you described i.e.

* If `failure_cancels_group` is `true`, only run the completion job after all jobs succeed
* If `failure_cancels_group` is `false`, only run the completion job after all jobs either succeed or permanently fail after exhausting their retry attempts.

It sounds like a bug that things aren't work that way! You up for submitting a PR?

**Comment by surjay** [comment]
Yep, I'd be happy to.

**Comment by jturkel** [comment]
Fixed in #13
