### ISSUE TITLE
Newest release of delayed_job_active_record breaks loading of delayed_job_groups_plugin

### ISSUE THREAD

**Issue by hoenth** [salsify/delayed_job_groups_plugin#17]
In version 4.15 of delayed_job_active_record, they have removed loading the Configure and Job classes until after initialization (https://github.com/collectiveidea/delayed_job_active_record/pull/172). 

This means that the Job class is not loaded with delayed_job_groups_plugin tries to access it on line 14 of lib/delayed_job_groups_plugin.rb. 

Other related libraries have encountered the same issue, such as delayed_cron_job (https://github.com/codez/delayed_cron_job/issues/27). 

Seems we could follow the same pattern as delayed_cron_job and check for `defined?(Rails::Railtie)` and if so, require a railtie file that waits until after initialization to `Delayed::Backend::ActiveRecord::Job.send(:include, Delayed::JobGroups::JobExtensions)`

If that makes sense, I am happy to work on it and issue a PR

**Comment by will89** [comment]
Fixed with https://github.com/salsify/delayed_job_groups_plugin/pull/18.
